### ISSUE TITLE
Coccinelle docs: confusing example

### ISSUE THREAD

**Issue by RalfJung** [Rust-for-Linux/rust-for-linux.com#13]
The docs at https://rust-for-linux.com/coccinelle-for-rust have this example:

> Merging some lifetimes in tokio:
> ```
> @@
> identifier f, P, p;
> type T1, T2;
> @@
> - f<P: T1>(p: P) -> T2
> + f(p: impl T1) -> T2
>      { ... }
> ```

However, there is not a single lifetime in this example, so it is unclear why this is described as "merging some lifetimes".

**Comment by ojeda** [comment]
Cc @JuliaLawall @TathagataRoy1278

**Comment by JuliaLawall** [comment]
Thanks for the feedback. I think that the example changed and the text remained the same.  We will come up with something better.

**Comment by ojeda** [comment]
Now fixed in the live webpage.

Thanks Ralf!
